---
title: "simulate data"
format: html
---

```{r}
source("data_simulation.R")
```

```{r}
set.seed(1337)
library(assertions)
data <- data_gen_censored(ns = 1000,
                  nv = 5,
                  conf = 0.5,
                  treat_prev = 1,
                  all_treat = FALSE,
                  all_control = FALSE,
                  censor = TRUE)
```


```{r}
set.seed(1337)
data3 <- TrialEmulation:::data_gen_censored(ns = 100,
                  nv = 5,
                  conf = 0.5,
                  treat_prev = 1,
                  all_treat = FALSE,
                  all_control = FALSE,
                  censor = TRUE)
```

```{r}
set.seed(1337)
t1 <- Sys.time()
data_treat <- TrialEmulation:::data_gen_censored(ns = 100000,
                  nv = 5,
                  conf = 0.5,
                  treat_prev = 1,
                  all_treat = TRUE,
                  all_control = FALSE,
                  censor = TRUE)
Sys.time() - t1 # 1.3s


data_cont <- TrialEmulation:::data_gen_censored(ns = 100,
                  nv = 5,
                  conf = 0.5,
                  treat_prev = 1,
                  all_treat = FALSE,
                  all_control = TRUE,
                  censor = TRUE)
```

